name: CSG
version: '${project.version}'
main: net.hgve.csg.CSG
api-version: '1.20'
author: [ HGVE, Zerek ]
description: A plugin for creative servers
website: https://hgve.net
commands:
  die:
    description: An way to kill yourself
  god:
    description: Become invincible
  feed:
    description: Fill hunger
  test:
    description: Funny test command
  setspawn:
    description: Sets spawn
  spawn:
    description: Makes you go to spawn
  home:
    description: Goes to home
  sethome:
    description: Set your home
  invtest:
    description: Inventory testing
  menu:
    description: Open a custom inventory
  ban:
    description: Ban a player
  unban:
    description: Unban a player
  banlist:
    description: Shows a list of the currently banned players